### ISSUE TITLE
input-gen blows up when field is missing description

### ISSUE THREAD

**Issue by joestubbs** [tapis-project/tapis-deployer#44]
For example, when running for the sdsc associate site, we got:
`
ERROR: field authenticator_dev_ldap_tenant_id missing description field. Deployer should be updated!
Traceback (most recent call last):
  File "/inputgen/input_generator.py", line 690, in <module>
    main()
  File "/inputgen/input_generator.py", line 675, in main
    user_dict, current_start_dict, quit_early = collect_user_dict(second_prompts, prev_start_dict, current_start_dict, user_dict)
  File "/inputgen/input_generator.py", line 486, in collect_user_dict
    main_prompt = f"({key}) " + description
TypeError: can only concatenate str (not "NoneType") to str
`

**Comment by joestubbs** [comment]
fixed by setting a default in case description is not provided:
`description = "(not provided)"`
